### ISSUE TITLE
Add a ToDo page

### ISSUE THREAD

**Issue by Industry4** [AlexJHawkins/Lesson1#3]
1. Add a page at [https://alexjhawkins.github.io/Lesson1/todo/](https://alexjhawkins.github.io/Lesson1/todo/)
2. Create a Hyperlink from the [Home Page](https://alexjhawkins.github.io/Lesson1/) to the [todo](https://alexjhawkins.github.io/Lesson1/todo/) page

- Use [w3schools](https://www.w3schools.com/html/html_links.asp) as reference for the hyperlinks

**Comment by AlexJHawkins** [comment]
This is now done
